server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/franz_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 147852369boss

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志打印（可选）
  mapper-locations: classpath:mapper/*.xml  # mapper文件路径配置（可选）
  type-aliases-package: com.franz.entity  # 实体类包路径（可选）

# 日志配置
logging:
  level:
    root: INFO
    com.franz: DEBUG  # 你的项目包名
    org.springframework.security: DEBUG  # 开发环境可以打印安全相关日志
  file:
    name: logs/application.log  # 日志文件路径
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 文件上传配置（如果需要）
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
